apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app-pod
  labels:
    app: frontend-app
  namespace: tarsidi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: frontend-app
        image: sidie88/frontend:angular
        env:
        - name: MY_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: BACKEND_URL
          value: http://backend-service.$(MY_NAMESPACE).svc.cluster.local
        ports:
        - containerPort: 4200
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  namespace: tarsidi
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 4200
  selector:
    app: frontend-app